### ISSUE TITLE
Add RSS feed?

### ISSUE THREAD

**Issue by Pat-Lafon** [aochagavia/ochagavia.nl#3]
Hey, I came across your blog, specifically https://ochagavia.nl/blog/an-adventure-with-optimization-rust-and-z3/ . Have you considered adding an RSS feed that can be subscribed to? To be honest, I'm not sure what's involved except the ease of use on my end of just copying website links and entering them into NetNewsWire.

**Comment by aochagavia** [comment]
Thanks for letting me know! Is something like [this link](https://ochagavia.nl/blog/index.xml) enough? I can add it to the website's menu, so people can find it

**Comment by Pat-Lafon** [comment]
Copying that link seems to have worked, thanks!

**Comment by aochagavia** [comment]
Great to hear! I also added it as a menu item so other people can find it 😉 (see https://github.com/aochagavia/ochagavia.nl/commit/1cfb647d45b7b6cbadc8c0bd6580d5440b48933a)
